#ifndef VMCALL_H_
#define VMCALL_H_

#include "vmmhelper.h"
#include "vmcallstructs.h"

#define VMCALL_GETVERSION 183
#define VMCALL_CHANGEPASSWORD 67
#define VMCALL_READ_PHYSICAL_MEMORY 241
#define VMCALL_WRITE_PHYSICAL_MEMORY 92
#define VMCALL_REDIRECTINT1 156
#define VMCALL_INT1REDIRECTED 74
#define VMCALL_CHANGESELECTORS 203
#define VMCALL_BLOCK_INTERRUPTS 45
#define VMCALL_RESTORE_INTERRUPTS 118

#define VMCALL_REGISTER_CR3_EDIT_CALLBACK 229
#define VMCALL_RETURN_FROM_CR3_EDIT_CALLBACK 81
#define VMCALL_GETCR0 167
#define VMCALL_GETCR3 58
#define VMCALL_GETCR4 214
#define VMCALL_RAISEPRIVILEGE 36
#define VMCALL_REDIRECTINT14 129
#define VMCALL_INT14REDIRECTED 195
#define VMCALL_REDIRECTINT3 83
#define VMCALL_INT3REDIRECTED 152

//dbvm v6+
#define VMCALL_READMSR 47
#define VMCALL_WRITEMSR 178

#define VMCALL_ULTIMAP 95
#define VMCALL_ULTIMAP_DISABLE 231


//dbvm v7
#define VMCALL_SWITCH_TO_KERNELMODE 64
#define VMCALL_DISABLE_DATAPAGEFAULTS 187
#define VMCALL_ENABLE_DATAPAGEFAULTS 52
#define VMCALL_GETLASTSKIPPEDPAGEFAULT 142

#define VMCALL_ULTIMAP_PAUSE 76
#define VMCALL_ULTIMAP_RESUME 209

#define VMCALL_ULTIMAP_DEBUGINFO 39

#define VMCALL_PSODTEST 164

//dbvm11
#define VMCALL_GETMEM 91
#define VMCALL_JTAGBREAK 225
#define VMCALL_GETNMICOUNT 63

#define VMCALL_WATCH_WRITES 134
#define VMCALL_WATCH_READS 88
#define VMCALL_WATCH_RETRIEVELOG 217
#define VMCALL_WATCH_DELETE 55

#define VMCALL_CLOAK_ACTIVATE 171
#define VMCALL_CLOAK_DEACTIVATE 42
#define VMCALL_CLOAK_READORIGINAL 126
#define VMCALL_CLOAK_WRITEORIGINAL 193

#define VMCALL_CLOAK_CHANGEREGONBP 71
#define VMCALL_CLOAK_REMOVECHANGEREGONBP 148

#define VMCALL_EPT_RESET 86

#define VMCALL_LOG_CR3VALUES_START 235
#define VMCALL_LOG_CR3VALUES_STOP 49

#define VMCALL_REGISTERPLUGIN 162
#define VMCALL_RAISEPMI 78
#define VMCALL_ULTIMAP2_HIDERANGEUSAGE 201

#define VMCALL_ADD_MEMORY 33
//#define VMCALL_DISABLE_EPT 58 dus nut wurk


#ifdef STATISTICS
#define VMCALL_GET_STATISTICS 159
#endif

#define VMCALL_WATCH_EXECUTES 84
#define VMCALL_SETTSCADJUST   227
#define VMCALL_SETSPEEDHACK   61
#define VMCALL_CAUSEDDEBUGBREAK 138

#define VMCALL_DISABLE_TSCADJUST 79

#define VMCALL_CLOAKEX_ACTIVATE 205

#define VMCALL_DISABLETSCHOOK 37
#define VMCALL_ENABLETSCHOOK 113

#define VMCALL_WATCH_GETSTATUS 191

#define VMCALL_CLOAK_TRACEONBP 56
#define VMCALL_CLOAK_TRACEONBP_REMOVE 175
#define VMCALL_CLOAK_TRACEONBP_READLOG 44
#define VMCALL_CLOAK_TRACEONBP_GETSTATUS 123
#define VMCALL_CLOAK_TRACEONBP_STOPTRACE 189

#define VMCALL_GETBROKENTHREADLISTSIZE 53
#define VMCALL_GETBROKENTHREADENTRYSHORT 169
#define VMCALL_GETBROKENTHREADENTRYFULL 41
#define VMCALL_SETBROKENTHREADENTRYFULL 115
#define VMCALL_RESUMEBROKENTHREAD 197


#define VMCALL_HIDEDBVMPHYSICALADDRESSES 69
#define VMCALL_HIDEDBVMPHYSICALADDRESSESALL 177

#define VMCALL_KERNELMODE 244
#define VMCALL_USERMODE 98

#define VMCALL_DEBUGLOG_SNAPSHOT 250
#define VMCALL_DEBUGLOG_CLEAR 251

#define VMCALL_DEBUG_SETSPINLOCKTIMEOUT 128


extern int hasEPTsupport;
extern int hasNPsupport;



int handleVMCall(pcpuinfo currentcpuinfo, VMRegisters *vmregisters);

void returnFromCR3Callback(pcpuinfo currentcpuinfo, VMRegisters *vmregisters, unsigned long long newcr3);
QWORD readMSRSafe(DWORD msr);
void writeMSRSafe(DWORD msr, QWORD value);

int raiseInvalidOpcodeException(pcpuinfo currentcpuinfo); //
int raisePagefault(pcpuinfo currentcpuinfo, UINT64 address);

void psod(void); //freezes DBVM

#endif /*VMCALL_H_*/
