name: Build DBVM Toolchain Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'docker/dbvm-build.Dockerfile'
      - '.github/workflows/build-dbvm-image.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Make a lowercase owner once, reuse everywhere.
      - name: Lowercase owner
        id: who
        shell: bash
        run: |
          owner="${{ github.repository_owner }}"
          echo "owner_lc=${owner,,}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.who.outputs.owner_lc }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/dbvm-build.Dockerfile
          push: true
          tags: ghcr.io/${{ steps.who.outputs.owner_lc }}/dbvm-build:jammy-gcc9-1
          provenance: false
