name: Build DBVM

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'dbvm/**'
      - '.github/workflows/build-dbvm.yml'

permissions: read-all

jobs:
  build-dbvm:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    container:
      image: ubuntu:24.04
      options: --privileged
    
    steps:
      - name: Install basic tools
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends \
            git \
            ca-certificates

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          apt-get install -y --no-install-recommends \
            gcc-9 \
            g++-9 \
            gcc-9-multilib \
            g++-9-multilib \
            build-essential \
            yasm \
            nasm \
            make \
            libc6-dev-i386

      - name: Verify compiler versions
        run: |
          gcc-9 --version
          g++-9 --version
          yasm --version
          nasm --version
          make --version

      - name: Set GCC 9 as default
        run: |
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90
          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
          gcc --version
          g++ --version

      - name: Build DBVM
        run: |
          cd dbvm
          make clean
          make install
        env:
          CC: gcc-9
          CXX: g++-9

      - name: List build outputs
        run: |
          ls -la dbvm/
          find dbvm -name "*.img" -o -name "*.bin" -o -name "*.rom" | head -20

      - name: Upload DBVM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DBVM-${{ github.sha }}
          path: |
            dbvm/vmdisk.img
            dbvm/vmdisk144.img
            dbvm/**/*.bin
          if-no-files-found: warn
